# Generated by Django 5.0.1 on 2026-04-01 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('EVENT_RETRY', 'Event Retry'), ('EVENT_BULK_RETRY', 'Bulk Event Retry')], max_length=50)),
                ('target_type', models.CharField(blank=True, choices=[('EVENT', 'Event')], max_length=50, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin'], name='security_ad_admin_i_53dca3_idx'), models.Index(fields=['action'], name='security_ad_action_15d526_idx'), models.Index(fields=['target_type'], name='security_ad_target__73d71d_idx'), models.Index(fields=['created_at'], name='security_ad_created_c3ccb5_idx')],
            },
        ),
    ]
