# Generated by Django 5.0.1 on 2026-04-01 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_RETRY', 'Event Retry'), ('EVENT_BULK_RETRY', 'Bulk Event Retry'), ('COURSE_CREATED', 'Course Created'), ('COURSE_PUBLISHED', 'Course Published'), ('MODULE_CREATED', 'Module Created'), ('LESSON_CREATED', 'Lesson Created'), ('LESSON_UPDATED', 'Lesson Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='target_type',
            field=models.CharField(blank=True, choices=[('EVENT', 'Event'), ('COURSE', 'Course'), ('MODULE', 'Module'), ('LESSON', 'Lesson')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='security_ad_target__d9d2a0_idx'),
        ),
    ]
