# Generated by Django 6.0.3 on 2026-03-29 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_user_id', models.CharField(max_length=100, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram_verified', models.BooleanField(default=False)),
                ('target_exam', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram'), ('ADMIN', 'Admin')], default='WEB', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='admission_a_email_98a22e_idx'), models.Index(fields=['status'], name='admission_a_status_6bc87b_idx'), models.Index(fields=['telegram_user_id'], name='admission_a_telegra_9b33bc_idx')],
            },
        ),
    ]
